// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtIl2mXyAEc-u8fTdoPnEfMgKxDdEMX7E',
    appId: '1:641705056447:web:98fbc67c8fe0a26c2c8e0a',
    messagingSenderId: '641705056447',
    projectId: 'youconapp-155b2',
    authDomain: 'youconapp-155b2.firebaseapp.com',
    storageBucket: 'youconapp-155b2.firebasestorage.app',
    measurementId: 'G-HEJPZ5JH08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB0V_hi2lXK4ay0kXM_sTyUx8JGWoyfkM',
    appId: '1:641705056447:android:394aae6baee18c612c8e0a',
    messagingSenderId: '641705056447',
    projectId: 'youconapp-155b2',
    storageBucket: 'youconapp-155b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xZvVoS-aQiLPwpBC_JaDGxsem7eSUA0',
    appId: '1:641705056447:ios:3d850cd7d7599c732c8e0a',
    messagingSenderId: '641705056447',
    projectId: 'youconapp-155b2',
    storageBucket: 'youconapp-155b2.firebasestorage.app',
    iosBundleId: 'com.example.youconappFlutter',
  );
}
