name: youconapp_flutter
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3

  # Estado y routing
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4

  # Utilidades
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3

  # PDF y reportes
  pdf: ^3.11.3
  printing: ^5.14.2

  # Gráficos
  fl_chart: ^1.1.0

  # Notificaciones locales
  flutter_local_notifications: ^17.2.3


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

 